pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'

                 bat 'npm init'
                 bat 'npm install cypress --save-dev'
            }
        }
   }
}
