 pipeline {
   agent any
   stages {
       stage('setup') {
         steps {
             browserstack(credentialsId: '<804693d5-c1cb-4bd1-9c12-bd400daace68>') {
                 echo "This is the config to use this test. :)"
                 
                 // add commands to run test
                 // Following are some of the example commands -----
                 sh 'npm install'
                 sh 'npm install --save path'
                 sh 'npm install @wdio/appium-service --save-dev'
                 sh 'npm install @wdio/browserstack-service --save-dev'
                 sh 'npm i @wdio/cli'
                 sh 'npm install --save-dev @wdio/local-runner'
                 sh 'npm install @wdio/mocha-framework --save-dev'
                 sh 'npm install @wdio/spec-reporter --save-dev'
             }
         }
        browserStackReportPublisher 'automate'
       }
     }
   }